Repository Engenheira-Coelho/O-que-as-mulheres-de-tech-querem, pull requests merged in 2022-10, with the labels that each got.

#1 Create the initial setup
  .gitignore
  README.md
  package-lock.json
  package.json
  public/index.html
  public/robots.txt
  src/App.js
  src/components/card/card.css
  src/components/card/card.js
  src/components/footer/footer.css
  src/components/footer/footer.js
  src/components/header/header.css
  src/components/header/header.js
  src/general/style/App.css
  src/general/style/index.css
  src/index.js
  src/reportWebVitals.js
  src/tests/App.test.js
  src/tests/setupTests.js
Labels: enhancement, hacktoberfest-accepted

#11 (en) - Creation of a basic structure for card component
  src/App.js
  src/components/card/card.css
  src/components/card/card.js
Labels: good first issue, hacktoberfest-accepted

#13 FEAT: Add new CSS to the header
  src/components/header/header.css
  src/components/header/header.js
Labels: enhancement, hacktoberfest-accepted

#20 Insere as imagens dos cards.
  src/general/images/img_card_1.png
  src/general/images/img_card_10.png
  src/general/images/img_card_11.png
  src/general/images/img_card_12.png
  src/general/images/img_card_13.png
  src/general/images/img_card_14.png
  src/general/images/img_card_15.png
  src/general/images/img_card_2.png
  src/general/images/img_card_3.png
  src/general/images/img_card_4.png
  src/general/images/img_card_5.png
  src/general/images/img_card_6.png
  src/general/images/img_card_7.png
  src/general/images/img_card_8.png
  src/general/images/img_card_9.png
Labels: hacktoberfest-accepted, iniciante|beginner, woman in tech

#22 Update the colors file
  src/general/palette.js
Labels: good first issue, hacktoberfest-accepted, iniciante|beginner, woman in tech

#24 Insere font-family
  src/general/fontFamily.js
Labels: good first issue, hacktoberfest-accepted, iniciante|beginner, woman in tech

#25 Insere participação no projeto
  README.md
Labels: good first issue, hacktoberfest-accepted, iniciante|beginner, woman in tech

#27 Passando props para o card component
  src/App.js
  src/components/card/card.css
  src/components/card/card.js
  src/general/situations.js
  src/general/situations.json
Labels: good first issue, hacktoberfest-accepted, pleno | mid-level, woman in tech

#28 14 - Main content
  src/App.js
  src/general/situations.js
Labels: enhancement, good first issue, hacktoberfest-accepted, senior, woman in tech

#29 Feat: Implement card hover with styled component
  package-lock.json
  package.json
  src/components/card/card.css
  src/components/card/card.js
Labels: hacktoberfest-accepted, woman in tech

#31 FEAT: create footer
  package-lock.json
  package.json
  src/components/footer/footer.css
  src/components/footer/footer.js
  src/components/footer/index.js
Labels: hacktoberfest-accepted, pleno | mid-level, woman in tech
